---
- name: Lanzar ping máquinas
  hosts: cliente1
  become: yes
  become_user: eman
  tasks:
    - name: Ping al cliente
      command: ping -c 4 192.168.1.138

    - name: Actualizar Paquetes
      expect:
        command: sudo apt update
        responses:
          "[sudo] contraseña para eman: ": usuariousuario

    - name: Instalación vsftpd
      apt:
        name: vsftpd
